Тема “Вычисления с помощью Numpy”

Задание 1.

In [105]:
import numpy as np

In [106]:
a = np.array([[ 1, 6],
[ 2, 8],
[ 3, 11],
[ 3, 10],
[ 1, 7]])

In [107]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2.

In [108]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3.

In [109]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [110]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

Задание 4.

In [111]:
b = np.cov(a.T)
b[0, 1]

2.0

Задание 5.

In [112]:
z = np.random.randint(-50, 51, 8)

print(z)

[ 18  18 -33 -23 -22  15  -6  -2]


In [113]:
np.where(z > 0)

(array([0, 1, 5], dtype=int64),)

Задание 6.

In [114]:
X = np.random.randint(0, 255, (10, 5))

print(X)

[[ 48 178  95  94 109]
 [194  28  50  66 120]
 [163 231 206 109   6]
 [181 161   6 107  20]
 [153   0  65 252 176]
 [149  54 220 121 175]
 [228 236  56  78 208]
 [189  52 174 227 254]
 [ 66 111  15 117 144]
 [149  35 181 189 143]]


In [115]:
mean_X = X.mean(axis=0)
mean_X

array([152. , 108.6, 106.8, 136. , 135.5])

In [116]:
std_X = X.std(axis=0)
std_X

array([53.01131955, 82.86881199, 76.78385247, 60.6052803 , 73.26697755])

In [117]:
X_standard = (X - mean_X) / std_X
X_standard

array([[-1.96184515,  0.83746826, -0.15367814, -0.69300892, -0.36169091],
       [ 0.79228362, -0.97262164, -0.73973887, -1.15501487, -0.21155506],
       [ 0.20750285,  1.47703336,  1.2919383 , -0.44550574, -1.76750842],
       [ 0.54705297,  0.63232474, -1.31277602, -0.47850616, -1.57642643],
       [ 0.0188639 , -1.31050509, -0.54438529,  1.91402464,  0.5527729 ],
       [-0.05659169, -0.65887273,  1.4742683 , -0.24750319,  0.53912419],
       [ 1.43365607,  1.53736969, -0.66159744, -0.95701232,  0.98953174],
       [ 0.69796414, -0.68300726,  0.87518401,  1.50151933,  1.61737257],
       [-1.62229503,  0.02896144, -1.19556387, -0.31350404,  0.11601407],
       [-0.05659169, -0.88815078,  0.96634901,  0.87451126,  0.10236535]])

In [118]:
X_standard.mean(axis=0)

array([ 7.63278329e-18,  7.77156117e-17,  4.44089210e-17, -1.11022302e-17,
       -8.32667268e-18])

In [119]:
X_standard.std(axis=0)

array([1., 1., 1., 1., 1.])

Задание 7.

In [120]:
x = np.random.randn(512)
x

array([-1.28594938e-01,  9.49464489e-01, -1.53981564e+00,  1.38490406e+00,
        8.90849266e-01, -2.90153534e-01,  6.94270824e-01, -9.14480756e-01,
        1.07842895e+00, -2.01276133e+00, -1.73997484e+00, -4.72168562e-01,
       -2.06908929e+00,  5.46887968e-01,  2.71395824e+00,  1.18098066e+00,
        1.32781851e+00,  6.69562242e-01, -1.21149520e+00,  7.81402993e-01,
       -1.17000551e+00, -2.22342376e+00, -2.05909822e+00, -1.72724212e+00,
       -5.28567490e-01,  3.29625423e-01, -3.60463197e-01, -4.19079897e-01,
       -7.66709011e-01, -4.13296590e-01, -3.02938497e-01, -4.66473872e-01,
       -1.52650911e+00,  6.12510313e-01,  5.95085953e-01,  2.03662584e-01,
       -6.54640680e-01, -7.45748648e-01, -1.54692970e+00, -1.02182535e+00,
       -1.71513251e+00,  9.05101524e-01, -1.62358077e+00,  1.55825452e+00,
       -1.88912154e-02,  1.72868712e+00,  8.23302130e-01, -9.50339139e-01,
        5.75520550e-01,  6.21098714e-01, -1.29680828e+00,  9.50576380e-01,
        5.19435814e-01,  

In [121]:
y = np.random.randn(512)
y

array([ 1.28910795,  1.31893911,  1.36208312,  0.04854767,  0.1359406 ,
       -1.36168183,  0.72523697,  0.28308548, -0.49160991,  0.26615938,
        0.09704911,  1.03457128,  0.18775448, -0.81147496, -0.29237305,
       -0.43915282,  1.47877715,  2.80487922,  1.25418662, -1.01668367,
       -0.69141474, -1.38971142, -1.66457691,  0.74075974,  1.49215285,
        1.79986064, -0.03861758,  0.26343581, -0.80117269,  0.76757642,
       -0.08572757, -0.10817274,  0.47633843, -0.67561469,  2.13367425,
       -1.45703008,  1.01886932, -1.04414289,  0.21233975,  0.08985889,
        0.22418393,  1.11961781,  0.84668852, -0.51775713,  0.34000436,
       -0.08294581,  0.01702592, -0.46187676, -0.74767683, -1.50448895,
       -1.1107316 ,  1.57687394,  0.17706791, -0.22447057,  0.85411798,
       -0.42986883, -0.45240359,  0.71390738, -0.79634233,  1.38183865,
       -2.03894459, -0.09718861,  1.19511686, -0.4508256 ,  0.5880953 ,
       -1.00880147, -2.28066166,  0.75849464,  0.20849935,  0.06

In [122]:
c = x - y
c

array([-1.41770289e+00, -3.69474618e-01, -2.90189876e+00,  1.33635639e+00,
        7.54908662e-01,  1.07152830e+00, -3.09661436e-02, -1.19756624e+00,
        1.57003886e+00, -2.27892071e+00, -1.83702395e+00, -1.50673984e+00,
       -2.25684377e+00,  1.35836293e+00,  3.00633129e+00,  1.62013348e+00,
       -1.50958641e-01, -2.13531698e+00, -2.46568181e+00,  1.79808667e+00,
       -4.78590772e-01, -8.33712335e-01, -3.94521310e-01, -2.46800186e+00,
       -2.02072034e+00, -1.47023522e+00, -3.21845616e-01, -6.82515704e-01,
        3.44636829e-02, -1.18087301e+00, -2.17210923e-01, -3.58301128e-01,
       -2.00284754e+00,  1.28812500e+00, -1.53858830e+00,  1.66069267e+00,
       -1.67351000e+00,  2.98394245e-01, -1.75926945e+00, -1.11168424e+00,
       -1.93931644e+00, -2.14516282e-01, -2.47026929e+00,  2.07601165e+00,
       -3.58895571e-01,  1.81163293e+00,  8.06276208e-01, -4.88462383e-01,
        1.32319738e+00,  2.12558766e+00, -1.86076688e-01, -6.26297559e-01,
        3.42367902e-01,  

In [123]:
np.sqrt((c**2).sum())

32.71363043527024

In [124]:
np.linalg.norm(x - y)

32.71363043527024

Задание 8. 

In [125]:
max = X.max(axis=0)
max

array([228, 236, 220, 252, 254])

In [126]:
min = X.min(axis=0)
min

array([48,  0,  6, 66,  6])

In [127]:
X_norm = ((X - min) / (max - min))
X_norm

array([[0.        , 0.75423729, 0.41588785, 0.15053763, 0.41532258],
       [0.81111111, 0.11864407, 0.20560748, 0.        , 0.45967742],
       [0.63888889, 0.97881356, 0.93457944, 0.2311828 , 0.        ],
       [0.73888889, 0.68220339, 0.        , 0.22043011, 0.05645161],
       [0.58333333, 0.        , 0.27570093, 1.        , 0.68548387],
       [0.56111111, 0.22881356, 1.        , 0.29569892, 0.68145161],
       [1.        , 1.        , 0.23364486, 0.06451613, 0.81451613],
       [0.78333333, 0.22033898, 0.78504673, 0.8655914 , 1.        ],
       [0.1       , 0.47033898, 0.04205607, 0.27419355, 0.55645161],
       [0.56111111, 0.14830508, 0.81775701, 0.66129032, 0.55241935]])

In [128]:
X_norm.max(), X_norm.min()

(1.0, 0.0)

Тема “Работа с данными в Pandas”

Задание 1.

In [129]:
import pandas as pd

In [130]:
authors = pd.DataFrame({'author_id': [1, 2, 3],'author_name': ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [131]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],'price': [450, 300, 350, 500, 450, 370, 290]})
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2.

In [132]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3.

In [133]:
top5 = authors_price.nlargest(5,'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4.

In [134]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

Задание 5.

In [135]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [136]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc='sum', fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [137]:
book_info.to_pickle('book_info.pkl')

In [138]:
book_info2 = pd.read_pickle('book_info.pkl')

In [139]:
book_info.equals(book_info2)

True

Задание 6.

In [140]:
df = pd.read_csv('C:\\Users\\tanbe\\Desktop\\netflix_titles.csv')

In [141]:
df.shape

(7787, 12)

в этом датасете представлено 7787 наблюдений и 12 признаков

In [142]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [143]:
df['type'].value_counts()

Movie      5377
TV Show    2410
Name: type, dtype: int64

в этом датасете представлено 2410 сериалов и 5377 фильмов  

In [144]:
missed_d = df['director'].isnull().sum()
print(f'Пропущенных значений (NaN) в признаке director: {missed_d}')

Пропущенных значений (NaN) в признаке director: 2389


In [145]:
missed_c = df['country'].isnull().sum()
print(f'Пропущенных значений (NaN) в признаке country: {missed_c}')

Пропущенных значений (NaN) в признаке country: 507


In [146]:
release_year = df.loc[df['release_year'] < 2003, 'release_year'].count()
print(f'Количество фильмов, выпущенных раньше 2003: {release_year}')

Количество фильмов, выпущенных раньше 2003: 564


In [147]:
df['country'].value_counts().nlargest(1)

United States    2555
Name: country, dtype: int64

США чаще всего выпускает фильмы на Netflix

Задание 7.

In [148]:
df['year_added'] = pd.DatetimeIndex(df['date_added']).year

In [149]:
df['month_added'] = pd.DatetimeIndex(df['date_added']).month

In [150]:
df['day_added'] = pd.DatetimeIndex(df['date_added']).day
df.head(5)

show_id     type  title           director  \
0      s1  TV Show     3%                NaN   
1      s2    Movie   7:19  Jorge Michel Grau   
2      s3    Movie  23:59       Gilbert Chan   
3      s4    Movie      9        Shane Acker   
4      s5    Movie     21     Robert Luketic   

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore   
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States   
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States   

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons   
1  December 23, 2016          2016  TV-MA     93 min   
2  December 20, 2018          2011      R     78 min   
3  November 16, 2017          2009  PG-13     80 min   
4    January 1, 2020          2008  PG-13    123 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   
3  Action & Adventure, Independent Movies, Sci-Fi...   
4                                             Dramas   

                                         description  year_added  month_added  \
0  In a future where the elite inhabit an island ...      2020.0          8.0   
1  After a devastating earthquake hits Mexico Cit...      2016.0         12.0   
2  When an army recruit is found dead, his fellow...      2018.0         12.0   
3  In a postapocalyptic world, rag-doll robots hi...      2017.0         11.0   
4  A brilliant group of students become card-coun...      2020.0          1.0   

   day_added  
0       14.0  
1       23.0  
2       20.0  
3       16.0  
4        1.0

Задание 8.

In [151]:
new_df = df.copy()

In [152]:
new_df = new_df.loc[new_df['country'].isin(['United States', 'India', 'United Kingdom']), :]

In [153]:
pd.pivot_table(new_df, values='title', index=['country', 'type'], aggfunc='count', columns=df['month_added'])

month_added             1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0   \
country        type                                                            
India          Movie      65    45    83    72    65    40    69    70    55   
               TV Show     2     2    12    14     5     7     7     4     1   
United Kingdom Movie      17    16    20    12    18    14     7    18    16   
               TV Show    13    17    34    14    10     7    16    22    19   
United States  Movie     245   118   156   139   109   112   144   143   128   
               TV Show    61    45    49    47    46    43    55    55    81   

month_added             10.0  11.0  12.0  
country        type                       
India          Movie      97    87   104  
               TV Show     8     3     6  
United Kingdom Movie      22     8    25  
               TV Show    22     9    20  
United States  Movie     172   210   174  
               TV Show    68    69    80